specVersion: 1.0.0
name: gafi-query
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.0.0"
  query:
    name: "@subql/query"
    version: "*"
description: SubQuery project for GAFI network
repository: 'https://github.com/cryptoviet/gafi-query'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://ws-testnet.gafi.network'
  genesisHash: '0x7d5f17bb816ab4d76c0c22268fa59bb4f56cfaec4d567bd21e21acfdd4982ae2'

  # Local env
  # endpoint: 'ws://host.docker.internal:9944'
  # genesisHash: '0x3e8b9c44d8e9a3f24947f70abb3eb2ececc33e4bb9ddccba6c3b27280358c5fa'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleCreateSponsoredPool
          kind: substrate/EventHandler
          filter:
            module: sponsoredPool
            method: CreatedPool
        - handler: handleUserJoinPool
          kind: substrate/EventHandler
          filter:
            module: pool
            method: Joined
        - handler: handleClaimContract
          kind: substrate/EventHandler
          filter:
            module: gameCreator
            method: Claimed
        - handler: handleChangeContractOwnership
          kind: substrate/EventHandler
          filter:
            module: gameCreator
            method: Changed
        - handler: handleSponsoredPoolNewTargets
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool
            method: newTargets
        - handler: handleSponsoredPoolWithdraw
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool
            method: withdrawPool
        - handler: handleChangePoolName
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool 
            method: setPoolName 
        - handler: handleClearPoolName
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool 
            method: clearPoolName 
        - handler: handleEvmContractCreated
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: Executed