specVersion: 1.0.0
name: gafi-query
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: ^0.33.0
  query:
    name: '@subql/query'
    version: 0.24.0
description: SubQuery project for GAFI network
repository: 'https://github.com/cryptoviet/gafi-query'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://ws-testnet.gafi.network'
  genesisHash: '0x17bdbb877b6010abb4c1d2b8295d23f08321b1ac3f9e7375ae6ec68d7e0ac988'

  # Local env
  # endpoint: 'ws://host.docker.internal:9944'
  # genesisHash: '0x3e8b9c44d8e9a3f24947f70abb3eb2ececc33e4bb9ddccba6c3b27280358c5fa'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleCreateSponsoredPool
          kind: substrate/EventHandler
          filter:
            module: sponsoredPool
            method: CreatedPool
        - handler: handleUserJoinPool
          kind: substrate/EventHandler
          filter:
            module: pool
            method: Joined
        - handler: handleClaimContract
          kind: substrate/EventHandler
          filter:
            module: gameCreator
            method: Claimed
        - handler: handleChangeContractOwnership
          kind: substrate/EventHandler
          filter:
            module: gameCreator
            method: Changed
        - handler: handleSponsoredPoolNewTargets
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool
            method: newTargets
        - handler: handleSponsoredPoolWithdraw
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool
            method: withdrawPool
        - handler: handleEvmContractCreated
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: Executed